name: Discord Issue Notification

on:
  issues:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_ISSUE }}
        run: |
          ISSUE_TYPE="${{ github.event_name }}"
          ISSUE_TITLE="${{ github.event.issue.title || github.event.pull_request.title }}"
          ISSUE_URL="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"
          AUTHOR="${{ github.actor }}"
          
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"GitHub Bot\", \"content\": \"📢 **${ISSUE_TYPE}** created by **${AUTHOR}**: **${ISSUE_TITLE}**\n🔗 ${ISSUE_URL}\"}" \
            "$DISCORD_WEBHOOK"
