name: Post to Facebook on Release

on:
  workflow_run:
    workflows:
      - Create Release
    types:
      - completed

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Publish to Facebook
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: |
          curl -i -X POST \
          "https://graph.facebook.com/v22.0/${{ env.FACEBOOK_PAGE_ID }}/feed" \
          -F "message=🎉 ${{ github.repository }} ${{ github.ref_name }} just released! 🎉 ${{ github.event.release.body }}" \
          -F "access_token=${{ env.FACEBOOK_ACCESS_TOKEN }}"