name: Tweet on Release

on:
  release:
    types: [published, created, edited, released, prereleased]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Send tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "🎉 New version of ${{ github.event.release.tag_name }} just released! 🚀\n\n${{ github.event.release.html_url }}"
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
