name: Run tests and upload coverage

on:
  workflow_call: # Trigger pro reusable workflow
    inputs:
      branch:
        required: false
        type: string
        default: "main"
      slug:
        required: false
        type: string
        default: ${{ github.repository }}

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -covermode=set ./... -coverprofile=coverage.txt

      - name: Check coverage file
        run: cat coverage.txt
      - name: Debug Codecov Upload
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          slug:  ${{ github.repository }}
          name: ${{ github.workflow }}
          fail_ci_if_error: true