name: Update Contributors
on:
  workflow_call: # Trigger pro reusable workflow
    inputs:
      branch:
        required: false
        type: string
        default: "${{ github.event.repository.default_branch }}"
      excludeBot:
        required: false
        type: boolean
        default: false
      notGenerateContributorsMd:
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * 1'  # Spouštět každý pondělí v 0:00
permissions:
  contents: write
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contributors
        uses: gouef/create-contributors-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}