name: Create Release

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: "${{ github.event.repository.default_branch }}"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: gouef/release-action@main
        with:
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}