name: Run tests and upload coverage

on:
  workflow_call: # Trigger pro reusable workflow
    inputs:
      branch:
        required: false
        type: string
        default: "main"
      slug:
        required: false
        type: string
        default: ${{ github.repository }}

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./tests -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug:  ${{ github.repository }}